name: CI

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'
env:
  CONFIGURATION: Release
  WORKING_DIRECTORY: C:\Users\niran\source\repos\ToDoApp
  Dotnet_version: 8.0.x
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.Dotnet_version}}

    - name: Build with dotnet# run the command for build the dotnet app
      run: dotnet build --configuration ${{env.CONFIGURATION}}

    - name: dotnet publish# run the command to pack the build files and dependencies into folder for deployment
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}

    - name: Upload artifact for deployment job#Reference a specific upload artifact
      uses: actions/upload-artifact@v2

      with:
        name: .net-apps
        path: ${{env.DOTNET_ROOT}}/publish
  
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/blazor_todo_app:${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/todoapp-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "miranjanhari123@gmail.com"
        git config --global user.name "Niranjanhari"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push 
